/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Lorenzo_Package;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;
/**
 *
 * @author moare
 */
public class SusConPanel extends javax.swing.JPanel implements IControllable{

    /**
     * Creates new form SusConPanel
     */
    private UserInterfaceController UICListener;
    private SusConFileReader scfr;
    
    public SusConPanel() {
        initComponents();
        scfr = new SusConFileReader();
        infoTA.setEditable(false); //prevents user from editing text field - can still be editing with code
        SolarPanelHS.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                infoTA.setText(scfr.getSusConSP());
                infoTA.setCaretPosition(0); //set text area scroll bar to top
            }
        });
        
        CompostHS.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                infoTA.setText(scfr.getSusConCT());
                infoTA.setCaretPosition(0); //set text area scroll bar to top
            }
        });
        
        RecycleHS.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                infoTA.setText(scfr.getSusConRB());
                infoTA.setCaretPosition(0); //set text area scroll bar to top
            }
        });
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    
    public void resetText(){
        infoTA.setText(scfr.getSusConIntro());
        infoTA.setCaretPosition(0); //set text area scroll bar to top
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SolarPanelHS = new javax.swing.JLabel();
        RecycleHS = new javax.swing.JLabel();
        CompostHS = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTA = new javax.swing.JTextArea();
        questionnaireBTN = new javax.swing.JButton();
        consultationBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        SolarPanelHS.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SolarPanelHS.setForeground(new java.awt.Color(204, 204, 255));
        add(SolarPanelHS);
        SolarPanelHS.setBounds(70, 200, 170, 50);
        add(RecycleHS);
        RecycleHS.setBounds(290, 310, 60, 60);
        add(CompostHS);
        CompostHS.setBounds(390, 260, 70, 100);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsibleconsumptionapp/Resources/Lorenzo_Resource/Images/SusCon - Copy.png"))); // NOI18N
        add(background);
        background.setBounds(10, 10, 490, 390);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        infoTA.setColumns(15);
        infoTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoTA.setRows(5);
        infoTA.setToolTipText("");
        jScrollPane1.setViewportView(infoTA);

        add(jScrollPane1);
        jScrollPane1.setBounds(510, 10, 370, 390);

        questionnaireBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        questionnaireBTN.setText("Questionnaire");
        questionnaireBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionnaireBTNActionPerformed(evt);
            }
        });
        add(questionnaireBTN);
        questionnaireBTN.setBounds(120, 420, 240, 40);

        consultationBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        consultationBTN.setText("Consultation");
        consultationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationBTNActionPerformed(evt);
            }
        });
        add(consultationBTN);
        consultationBTN.setBounds(530, 420, 240, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void questionnaireBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionnaireBTNActionPerformed
        // TODO add your handling code here:
        UICListener.changePanel("SusConQuestionnaire");
    }//GEN-LAST:event_questionnaireBTNActionPerformed

    private void consultationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationBTNActionPerformed
        // TODO add your handling code here:
        UICListener.changePanel("SusConConsultation");
    }//GEN-LAST:event_consultationBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompostHS;
    private javax.swing.JLabel RecycleHS;
    private javax.swing.JLabel SolarPanelHS;
    private javax.swing.JLabel background;
    private javax.swing.JButton consultationBTN;
    private javax.swing.JTextArea infoTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton questionnaireBTN;
    // End of variables declaration//GEN-END:variables
}
