/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Lorenzo_Package;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;
/**
 *
 * @author moare
 */
public class SusConPanel extends javax.swing.JPanel implements IControllable{

    /**
     * Creates new form SusConPanel
     */
    private UserInterfaceController UICListener;
    public SusConPanel() {
        initComponents();
        
        hotspot1.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e) {
                infoTA.setText("Solar Panel Clicked");
            }
        });
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotspot1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        hotspot1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        hotspot1.setForeground(new java.awt.Color(204, 204, 255));
        hotspot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsibleconsumptionapp/Resources/Lorenzo_Resource/Images/SolarPanel.png"))); // NOI18N
        add(hotspot1);
        hotspot1.setBounds(120, 70, 80, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsibleconsumptionapp/Resources/Lorenzo_Resource/Images/SusCon.png"))); // NOI18N
        add(background);
        background.setBounds(10, 10, 600, 390);

        infoTA.setColumns(15);
        infoTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        infoTA.setRows(5);
        jScrollPane1.setViewportView(infoTA);

        add(jScrollPane1);
        jScrollPane1.setBounds(620, 10, 200, 390);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Questionaire");
        add(jButton1);
        jButton1.setBounds(330, 420, 180, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel hotspot1;
    private javax.swing.JTextArea infoTA;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
