/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Lorenzo_Package;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;
import responsibleconsumptionapp.Lorenzo_Package.Model.EnergyConsultation;
import responsibleconsumptionapp.Model.User;

/**
 *
 * @author moare
 */
public class SusConConsultation extends javax.swing.JPanel implements IControllable {
    private UserInterfaceController UICListener;
    private EnergyConsultation ec;
    private User user;
    /**
     * Creates new form SusConConsultation
     */
    public SusConConsultation() {
        initComponents();
        //hide radio button associate labels and text fields
        spQuantityLBL.setVisible(false);
        spQuantityTF.setVisible(false);
        spTypeLBL.setVisible(false);
        spTypeList.setVisible(false);
        spTypePane.setVisible(false);
        
        recycleGBQLBL.setVisible(false);
        recycleGBQTF.setVisible(false);
        recycleBBQLBL.setVisible(false);
        recycleBBQTF.setVisible(false);
        recycleWeightLBL.setVisible(false);
        recycleWeightTF.setVisible(false);
        recycleIntervalLBL.setVisible(false);
        recycleIntervalTF.setVisible(false);
        
        compostLengthLBL.setVisible(false);
        compostLengthTF.setVisible(false);
        compostWidthLBL.setVisible(false);
        compostWidthTF.setVisible(false);
        compostFrameLBL.setVisible(false);
        compostFrameList.setVisible(false);
        compostFramePane.setVisible(false);
    }
    
    public void setUser(){
        user = this.UICListener.getUser();
        fullnameTF.setText(user.getName());
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeBG = new javax.swing.ButtonGroup();
        typeLBL = new javax.swing.JLabel();
        solarRB = new javax.swing.JRadioButton();
        recycleRB = new javax.swing.JRadioButton();
        compostRB = new javax.swing.JRadioButton();
        AddressLBL = new javax.swing.JLabel();
        detailsLBL = new javax.swing.JLabel();
        add1LBL = new javax.swing.JLabel();
        fullnameLBL = new javax.swing.JLabel();
        fullnameTF = new javax.swing.JTextField();
        add1TF = new javax.swing.JTextField();
        add2LBL = new javax.swing.JLabel();
        add2TF = new javax.swing.JTextField();
        countyLBL = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        cityLBL = new javax.swing.JLabel();
        countyTF = new javax.swing.JTextField();
        eircodeLBL = new javax.swing.JLabel();
        eircodeTF = new javax.swing.JTextField();
        spQuantityTF = new javax.swing.JTextField();
        spQuantityLBL = new javax.swing.JLabel();
        submitBTN = new javax.swing.JButton();
        spTypePane = new javax.swing.JScrollPane();
        spTypeList = new javax.swing.JList<>();
        spTypeLBL = new javax.swing.JLabel();
        recycleGBQLBL = new javax.swing.JLabel();
        recycleBBQLBL = new javax.swing.JLabel();
        recycleWeightLBL = new javax.swing.JLabel();
        recycleIntervalLBL = new javax.swing.JLabel();
        recycleGBQTF = new javax.swing.JTextField();
        recycleBBQTF = new javax.swing.JTextField();
        recycleWeightTF = new javax.swing.JTextField();
        recycleIntervalTF = new javax.swing.JTextField();
        compostFrameLBL = new javax.swing.JLabel();
        compostLengthLBL = new javax.swing.JLabel();
        compostWidthLBL = new javax.swing.JLabel();
        compostLengthTF = new javax.swing.JTextField();
        compostWidthTF = new javax.swing.JTextField();
        compostFramePane = new javax.swing.JScrollPane();
        compostFrameList = new javax.swing.JList<>();

        typeLBL.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        typeLBL.setText("Type of Renewable Energy Solution");

        typeBG.add(solarRB);
        solarRB.setText("Solar Panel");
        solarRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solarRBActionPerformed(evt);
            }
        });

        typeBG.add(recycleRB);
        recycleRB.setText("Recycling");
        recycleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycleRBActionPerformed(evt);
            }
        });

        typeBG.add(compostRB);
        compostRB.setText("Composting");
        compostRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compostRBActionPerformed(evt);
            }
        });

        AddressLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddressLBL.setText("Address");

        detailsLBL.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        detailsLBL.setText("Personal Details");

        add1LBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add1LBL.setText("Address Line 1:");

        fullnameLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullnameLBL.setText("Fullname: ");

        fullnameTF.setText("FULLNAME");

        add2LBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add2LBL.setText("Address Line 2:");

        countyLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        countyLBL.setText("County:");

        cityLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cityLBL.setText("City:");

        eircodeLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eircodeLBL.setText("Eircode:");

        spQuantityTF.setText("0");
        spQuantityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spQuantityTFActionPerformed(evt);
            }
        });

        spQuantityLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spQuantityLBL.setText("Quantity: ");

        submitBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        spTypeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Roof", "Ground", "Pole" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spTypePane.setViewportView(spTypeList);

        spTypeLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spTypeLBL.setText("Type:");

        recycleGBQLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recycleGBQLBL.setText("Green Bin Quantity:");

        recycleBBQLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recycleBBQLBL.setText("Brown Bin Quantity:");

        recycleWeightLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recycleWeightLBL.setText("Weight:");

        recycleIntervalLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recycleIntervalLBL.setText("Interval:");

        recycleGBQTF.setText("0");
        recycleGBQTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycleGBQTFActionPerformed(evt);
            }
        });

        recycleBBQTF.setText("0");

        recycleWeightTF.setText("0");
        recycleWeightTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycleWeightTFActionPerformed(evt);
            }
        });

        recycleIntervalTF.setText("0");

        compostFrameLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        compostFrameLBL.setText("Frame Type:");

        compostLengthLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        compostLengthLBL.setText("Length:");

        compostWidthLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        compostWidthLBL.setText("Width:");

        compostLengthTF.setText("0");
        compostLengthTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compostLengthTFActionPerformed(evt);
            }
        });

        compostWidthTF.setText("0");

        compostFrameList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Wood", "Concrete", "Plastic" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        compostFramePane.setViewportView(compostFrameList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeLBL)
                        .addGap(157, 157, 157)
                        .addComponent(detailsLBL)
                        .addContainerGap(195, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recycleRB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(recycleGBQLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recycleGBQTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(compostRB)
                            .addComponent(solarRB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spQuantityLBL)
                                    .addComponent(spTypeLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spTypePane, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(compostFrameLBL)
                                    .addGap(18, 18, 18)
                                    .addComponent(compostFramePane, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(recycleBBQLBL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(recycleBBQTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(compostLengthLBL)
                                            .addGap(47, 47, 47))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(compostWidthLBL)
                                            .addGap(51, 51, 51)))
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(compostWidthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(compostLengthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recycleIntervalLBL)
                                    .addComponent(recycleWeightLBL))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recycleWeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recycleIntervalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddressLBL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fullnameLBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fullnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(add1LBL)
                                            .addComponent(add2LBL)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cityLBL)
                                                .addComponent(countyLBL)
                                                .addComponent(eircodeLBL)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(eircodeTF)
                                                        .addComponent(countyTF)
                                                        .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(add1TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(add2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLBL)
                    .addComponent(detailsLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fullnameLBL)
                            .addComponent(fullnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add1LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add2LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cityLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countyLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eircodeLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eircodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(solarRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recycleRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compostRB)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spQuantityLBL)
                            .addComponent(spQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spTypePane, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spTypeLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recycleGBQLBL)
                            .addComponent(recycleGBQTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recycleBBQLBL)
                            .addComponent(recycleBBQTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recycleWeightLBL)
                            .addComponent(recycleWeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recycleIntervalLBL)
                            .addComponent(recycleIntervalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compostLengthLBL)
                            .addComponent(compostLengthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compostWidthLBL)
                            .addComponent(compostWidthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(compostFrameLBL))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(compostFramePane, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        ec = new EnergyConsultation(fullnameTF.getText(), add1TF.getText(), add2TF.getText(), cityTF.getText(), countyTF.getText(), eircodeTF.getText());
        System.out.println(ec);
    }//GEN-LAST:event_submitBTNActionPerformed

    private void solarRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solarRBActionPerformed
        // TODO add your handling code here:
        spQuantityLBL.setVisible(true);
        spQuantityTF.setVisible(true);
        spTypeLBL.setVisible(true);
        spTypeList.setVisible(true);
        spTypePane.setVisible(true);
        
        recycleGBQLBL.setVisible(false);
        recycleGBQTF.setVisible(false);
        recycleBBQLBL.setVisible(false);
        recycleBBQTF.setVisible(false);
        recycleWeightLBL.setVisible(false);
        recycleWeightTF.setVisible(false);
        recycleIntervalLBL.setVisible(false);
        recycleIntervalTF.setVisible(false);
        
        compostLengthLBL.setVisible(false);
        compostLengthTF.setVisible(false);
        compostWidthLBL.setVisible(false);
        compostWidthTF.setVisible(false);
        compostFrameLBL.setVisible(false);
        compostFrameList.setVisible(false);
        compostFramePane.setVisible(false);
    }//GEN-LAST:event_solarRBActionPerformed

    private void spQuantityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spQuantityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spQuantityTFActionPerformed

    private void recycleGBQTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycleGBQTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycleGBQTFActionPerformed

    private void recycleWeightTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycleWeightTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycleWeightTFActionPerformed

    private void recycleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycleRBActionPerformed
        // TODO add your handling code here:
        recycleGBQLBL.setVisible(true);
        recycleGBQTF.setVisible(true);
        recycleBBQLBL.setVisible(true);
        recycleBBQTF.setVisible(true);
        recycleWeightLBL.setVisible(true);
        recycleWeightTF.setVisible(true);
        recycleIntervalLBL.setVisible(true);
        recycleIntervalTF.setVisible(true);
        
        spQuantityLBL.setVisible(false);
        spQuantityTF.setVisible(false);
        spTypeLBL.setVisible(false);
        spTypeList.setVisible(false);
        spTypePane.setVisible(false);
        
        compostLengthLBL.setVisible(false);
        compostLengthTF.setVisible(false);
        compostWidthLBL.setVisible(false);
        compostWidthTF.setVisible(false);
        compostFrameLBL.setVisible(false);
        compostFrameList.setVisible(false);
        compostFramePane.setVisible(false);
    }//GEN-LAST:event_recycleRBActionPerformed

    private void compostLengthTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compostLengthTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compostLengthTFActionPerformed

    private void compostRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compostRBActionPerformed
        // TODO add your handling code here:
        compostLengthLBL.setVisible(true);
        compostLengthTF.setVisible(true);
        compostWidthLBL.setVisible(true);
        compostWidthTF.setVisible(true);
        compostFrameLBL.setVisible(true);
        compostFrameList.setVisible(true);
        compostFramePane.setVisible(true);
        
        spQuantityLBL.setVisible(false);
        spQuantityTF.setVisible(false);
        spTypeLBL.setVisible(false);
        spTypeList.setVisible(false);
        spTypePane.setVisible(false);
        
        recycleGBQLBL.setVisible(false);
        recycleGBQTF.setVisible(false);
        recycleBBQLBL.setVisible(false);
        recycleBBQTF.setVisible(false);
        recycleWeightLBL.setVisible(false);
        recycleWeightTF.setVisible(false);
        recycleIntervalLBL.setVisible(false);
        recycleIntervalTF.setVisible(false);
    }//GEN-LAST:event_compostRBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLBL;
    private javax.swing.JLabel add1LBL;
    private javax.swing.JTextField add1TF;
    private javax.swing.JLabel add2LBL;
    private javax.swing.JTextField add2TF;
    private javax.swing.JLabel cityLBL;
    private javax.swing.JTextField cityTF;
    private javax.swing.JLabel compostFrameLBL;
    private javax.swing.JList<String> compostFrameList;
    private javax.swing.JScrollPane compostFramePane;
    private javax.swing.JLabel compostLengthLBL;
    private javax.swing.JTextField compostLengthTF;
    private javax.swing.JRadioButton compostRB;
    private javax.swing.JLabel compostWidthLBL;
    private javax.swing.JTextField compostWidthTF;
    private javax.swing.JLabel countyLBL;
    private javax.swing.JTextField countyTF;
    private javax.swing.JLabel detailsLBL;
    private javax.swing.JLabel eircodeLBL;
    private javax.swing.JTextField eircodeTF;
    private javax.swing.JLabel fullnameLBL;
    private javax.swing.JTextField fullnameTF;
    private javax.swing.JLabel recycleBBQLBL;
    private javax.swing.JTextField recycleBBQTF;
    private javax.swing.JLabel recycleGBQLBL;
    private javax.swing.JTextField recycleGBQTF;
    private javax.swing.JLabel recycleIntervalLBL;
    private javax.swing.JTextField recycleIntervalTF;
    private javax.swing.JRadioButton recycleRB;
    private javax.swing.JLabel recycleWeightLBL;
    private javax.swing.JTextField recycleWeightTF;
    private javax.swing.JRadioButton solarRB;
    private javax.swing.JLabel spQuantityLBL;
    private javax.swing.JTextField spQuantityTF;
    private javax.swing.JLabel spTypeLBL;
    private javax.swing.JList<String> spTypeList;
    private javax.swing.JScrollPane spTypePane;
    private javax.swing.JButton submitBTN;
    private javax.swing.ButtonGroup typeBG;
    private javax.swing.JLabel typeLBL;
    // End of variables declaration//GEN-END:variables
}
