/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Lorenzo_Package;

import javax.swing.JOptionPane;
import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *
 * @author moare
 */
public class SusConQuestionnaire extends javax.swing.JPanel implements IControllable{

    /**
     * Creates new form SusConQuestionnaire
     */
    private UserInterfaceController UICListener;
    
    public SusConQuestionnaire() {
        initComponents();
        q1TA.setEditable(false);
        q2TA.setEditable(false);
        q3TA.setEditable(false);
        q4TA.setEditable(false);
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1BG = new javax.swing.ButtonGroup();
        q2BG = new javax.swing.ButtonGroup();
        q3BG = new javax.swing.ButtonGroup();
        q4BG = new javax.swing.ButtonGroup();
        q1LBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        q1TA = new javax.swing.JTextArea();
        q1RadioA = new javax.swing.JRadioButton();
        q1RadioB = new javax.swing.JRadioButton();
        q1RadioC = new javax.swing.JRadioButton();
        q2LBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        q2TA = new javax.swing.JTextArea();
        q2RadioC = new javax.swing.JRadioButton();
        q2RadioA = new javax.swing.JRadioButton();
        q2RadioB = new javax.swing.JRadioButton();
        q3LBL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        q3TA = new javax.swing.JTextArea();
        q3RadioC = new javax.swing.JRadioButton();
        q3RadioA = new javax.swing.JRadioButton();
        q3RadioB = new javax.swing.JRadioButton();
        submitBTN = new javax.swing.JButton();
        q4LBL = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        q4TA = new javax.swing.JTextArea();
        q4RadioC = new javax.swing.JRadioButton();
        q4RadioA = new javax.swing.JRadioButton();
        q4RadioB = new javax.swing.JRadioButton();
        q4RadioD = new javax.swing.JRadioButton();
        returnBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        q1LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1LBL.setText("Question 1 - ");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));

        q1TA.setColumns(20);
        q1TA.setRows(2);
        q1TA.setText("Which of these is not a benefit of Solar Panels?");
        jScrollPane1.setViewportView(q1TA);

        q1BG.add(q1RadioA);
        q1RadioA.setText("Selling excess power back to the grid");

        q1BG.add(q1RadioB);
        q1RadioB.setText("Reducing electricty bills");

        q1BG.add(q1RadioC);
        q1RadioC.setText("High installation costs");

        q2LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q2LBL.setText("Question 2 - ");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));

        q2TA.setColumns(20);
        q2TA.setRows(2);
        q2TA.setText("Which of the following is an ecological benefit of properly disposing of non-recyclable waste?");
        jScrollPane2.setViewportView(q2TA);

        q2BG.add(q2RadioC);
        q2RadioC.setText("Fines for non-compliance");

        q2BG.add(q2RadioA);
        q2RadioA.setText("More space in the black bin");

        q2BG.add(q2RadioB);
        q2RadioB.setText("Prevents leeching of harmful chemicals into the ground");

        q3LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3LBL.setText("Question 3 - ");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));

        q3TA.setColumns(20);
        q3TA.setRows(2);
        q3TA.setText("Which of the following can be used in an organic waste compost garden?");
        jScrollPane3.setViewportView(q3TA);

        q3BG.add(q3RadioC);
        q3RadioC.setText("Produce stickers");

        q3BG.add(q3RadioA);
        q3RadioA.setText("Eggshells");

        q3BG.add(q3RadioB);
        q3RadioB.setText("Empty plastic bottles");

        submitBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        q4LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q4LBL.setText("Question 4 -");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));

        q4TA.setColumns(20);
        q4TA.setRows(2);
        q4TA.setText("Given the information provided which of the following renewable energy soltutions is a source of positive contribution to\nyour local community?");
        jScrollPane4.setViewportView(q4TA);

        q4BG.add(q4RadioC);
        q4RadioC.setText("Composting");

        q4BG.add(q4RadioA);
        q4RadioA.setText("Solar Panels");

        q4BG.add(q4RadioB);
        q4RadioB.setText("Recycling");

        q4BG.add(q4RadioD);
        q4RadioD.setText("All of the above");

        returnBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnBTN.setText("Return");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q2LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q2RadioA)
                                .addGap(18, 18, 18)
                                .addComponent(q2RadioB)
                                .addGap(18, 18, 18)
                                .addComponent(q2RadioC))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q1LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q1RadioA)
                                .addGap(18, 18, 18)
                                .addComponent(q1RadioB)
                                .addGap(18, 18, 18)
                                .addComponent(q1RadioC))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q3LBL)
                                    .addComponent(q4LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(returnBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(q3RadioA)
                                    .addGap(18, 18, 18)
                                    .addComponent(q3RadioB)
                                    .addGap(18, 18, 18)
                                    .addComponent(q3RadioC))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(q4RadioA)
                                    .addGap(18, 18, 18)
                                    .addComponent(q4RadioB)
                                    .addGap(18, 18, 18)
                                    .addComponent(q4RadioC)
                                    .addGap(18, 18, 18)
                                    .addComponent(q4RadioD))
                                .addComponent(jScrollPane4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1RadioA)
                    .addComponent(q1RadioB)
                    .addComponent(q1RadioC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2RadioA)
                    .addComponent(q2RadioB)
                    .addComponent(q2RadioC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3RadioA)
                    .addComponent(q3RadioB)
                    .addComponent(q3RadioC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q4LBL)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4RadioA)
                    .addComponent(q4RadioB)
                    .addComponent(q4RadioC)
                    .addComponent(q4RadioD))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        //following used to calculate correct answers and final score
        int score = 0;
        if(q1RadioC.isSelected()) {
            score += 5;
        }
        if(q2RadioB.isSelected()) {
            score += 5;
        }
        if(q3RadioA.isSelected()) {
            score += 5;
        }
        if(q4RadioD.isSelected()) {
            score += 5;
        }
        int correctAnswers = score/5;
        JOptionPane.showMessageDialog(this,correctAnswers+" Answers Correct. "+score+" Eco-Friendly Points have been added to your account.");
        UICListener.changePanel("SusCon");
    }//GEN-LAST:event_submitBTNActionPerformed

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTNActionPerformed
        // TODO add your handling code here:
        UICListener.changePanel("SusCon");
    }//GEN-LAST:event_returnBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.ButtonGroup q1BG;
    private javax.swing.JLabel q1LBL;
    private javax.swing.JRadioButton q1RadioA;
    private javax.swing.JRadioButton q1RadioB;
    private javax.swing.JRadioButton q1RadioC;
    private javax.swing.JTextArea q1TA;
    private javax.swing.ButtonGroup q2BG;
    private javax.swing.JLabel q2LBL;
    private javax.swing.JRadioButton q2RadioA;
    private javax.swing.JRadioButton q2RadioB;
    private javax.swing.JRadioButton q2RadioC;
    private javax.swing.JTextArea q2TA;
    private javax.swing.ButtonGroup q3BG;
    private javax.swing.JLabel q3LBL;
    private javax.swing.JRadioButton q3RadioA;
    private javax.swing.JRadioButton q3RadioB;
    private javax.swing.JRadioButton q3RadioC;
    private javax.swing.JTextArea q3TA;
    private javax.swing.ButtonGroup q4BG;
    private javax.swing.JLabel q4LBL;
    private javax.swing.JRadioButton q4RadioA;
    private javax.swing.JRadioButton q4RadioB;
    private javax.swing.JRadioButton q4RadioC;
    private javax.swing.JRadioButton q4RadioD;
    private javax.swing.JTextArea q4TA;
    private javax.swing.JButton returnBTN;
    private javax.swing.JButton submitBTN;
    // End of variables declaration//GEN-END:variables
}
