/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Lorenzo_Package;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *
 * @author moare
 */
public class SusConQuestionaire extends javax.swing.JPanel implements IControllable{

    /**
     * Creates new form SusConQuestionaire
     */
    private UserInterfaceController UICListener;
    
    public SusConQuestionaire() {
        initComponents();
        q1TA.setEditable(false);
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1BG = new javax.swing.ButtonGroup();
        q2BG = new javax.swing.ButtonGroup();
        q3BG = new javax.swing.ButtonGroup();
        q1LBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        q1TA = new javax.swing.JTextArea();
        q1RadioA = new javax.swing.JRadioButton();
        q1RadioB = new javax.swing.JRadioButton();
        q1RadioC = new javax.swing.JRadioButton();
        q2LBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        q2TA = new javax.swing.JTextArea();
        q2RadioC = new javax.swing.JRadioButton();
        q2RadioA = new javax.swing.JRadioButton();
        q2RadioB = new javax.swing.JRadioButton();
        q3LBL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        q3TA = new javax.swing.JTextArea();
        q3RadioC = new javax.swing.JRadioButton();
        q3RadioA = new javax.swing.JRadioButton();
        q3RadioB = new javax.swing.JRadioButton();
        submitBTN = new javax.swing.JButton();

        q1LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q1LBL.setText("Question 1 - ");

        q1TA.setColumns(20);
        q1TA.setRows(2);
        q1TA.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.");
        jScrollPane1.setViewportView(q1TA);

        q1BG.add(q1RadioA);
        q1RadioA.setText("Answer A");

        q1BG.add(q1RadioB);
        q1RadioB.setText("Answer B");

        q1BG.add(q1RadioC);
        q1RadioC.setText("Answer C");

        q2LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q2LBL.setText("Question 2 - ");

        q2TA.setColumns(20);
        q2TA.setRows(2);
        q2TA.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.");
        jScrollPane2.setViewportView(q2TA);

        q2BG.add(q2RadioC);
        q2RadioC.setText("Answer C");

        q2BG.add(q2RadioA);
        q2RadioA.setText("Answer A");

        q2BG.add(q2RadioB);
        q2RadioB.setText("Answer B");

        q3LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        q3LBL.setText("Question 3 - ");

        q3TA.setColumns(20);
        q3TA.setRows(2);
        q3TA.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.");
        jScrollPane3.setViewportView(q3TA);

        q3BG.add(q3RadioC);
        q3RadioC.setText("Answer C");

        q3BG.add(q3RadioA);
        q3RadioA.setText("Answer A");

        q3BG.add(q3RadioB);
        q3RadioB.setText("Answer B");

        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q1LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(q1RadioA)
                                .addGap(18, 18, 18)
                                .addComponent(q1RadioB)
                                .addGap(18, 18, 18)
                                .addComponent(q1RadioC))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q2LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q2RadioA)
                                .addGap(18, 18, 18)
                                .addComponent(q2RadioB)
                                .addGap(18, 18, 18)
                                .addComponent(q2RadioC))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q3LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q3RadioA)
                                .addGap(18, 18, 18)
                                .addComponent(q3RadioB)
                                .addGap(18, 18, 18)
                                .addComponent(q3RadioC))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1RadioA)
                    .addComponent(q1RadioB)
                    .addComponent(q1RadioC))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2RadioA)
                    .addComponent(q2RadioB)
                    .addComponent(q2RadioC))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3RadioA)
                    .addComponent(q3RadioB)
                    .addComponent(q3RadioC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.ButtonGroup q1BG;
    private javax.swing.JLabel q1LBL;
    private javax.swing.JRadioButton q1RadioA;
    private javax.swing.JRadioButton q1RadioB;
    private javax.swing.JRadioButton q1RadioC;
    private javax.swing.JTextArea q1TA;
    private javax.swing.ButtonGroup q2BG;
    private javax.swing.JLabel q2LBL;
    private javax.swing.JRadioButton q2RadioA;
    private javax.swing.JRadioButton q2RadioB;
    private javax.swing.JRadioButton q2RadioC;
    private javax.swing.JTextArea q2TA;
    private javax.swing.ButtonGroup q3BG;
    private javax.swing.JLabel q3LBL;
    private javax.swing.JRadioButton q3RadioA;
    private javax.swing.JRadioButton q3RadioB;
    private javax.swing.JRadioButton q3RadioC;
    private javax.swing.JTextArea q3TA;
    private javax.swing.JButton submitBTN;
    // End of variables declaration//GEN-END:variables
}
