/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Aaron_Package;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *
 * @author gamer
 */
public class bikeBookingGUI extends javax.swing.JPanel implements IControllable{

    /**
     * Creates new form bikeBookingGUI
     */
    private UserInterfaceController UICListener;

    public bikeBookingGUI() {
        initComponents();
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        welcomeBikeLb = new javax.swing.JLabel();
        startLocLbl = new javax.swing.JLabel();
        endLocLbl = new javax.swing.JLabel();
        heustonStartBtn = new javax.swing.JRadioButton();
        connollyStartBtn = new javax.swing.JRadioButton();
        nciStartBtn = new javax.swing.JRadioButton();
        jervisStartBtn = new javax.swing.JRadioButton();
        stephenStartBtn = new javax.swing.JRadioButton();
        heustonEndBtn = new javax.swing.JRadioButton();
        connollyEndBtn = new javax.swing.JRadioButton();
        nciEndBtn = new javax.swing.JRadioButton();
        jervisEndBtn = new javax.swing.JRadioButton();
        stephenEndBtn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bikeTxtOutput = new javax.swing.JTextArea();

        welcomeBikeLb.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        welcomeBikeLb.setText("Welcome to the Bike Booking App");
        welcomeBikeLb.setAlignmentX(0.5F);

        startLocLbl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        startLocLbl.setText("Please select your starting location");

        endLocLbl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        endLocLbl.setText("Please select your ending location");

        heustonStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        heustonStartBtn.setText("Heuston Station");

        connollyStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        connollyStartBtn.setText("Connolly Station");

        nciStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nciStartBtn.setText("NCI");

        jervisStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jervisStartBtn.setText("Jervis");
        jervisStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jervisStartBtnActionPerformed(evt);
            }
        });

        stephenStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        stephenStartBtn.setText("Stephen's Green");

        heustonEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        heustonEndBtn.setText("Heuston Station");

        connollyEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        connollyEndBtn.setText("Connolly Station");

        nciEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nciEndBtn.setText("NCI");

        jervisEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jervisEndBtn.setText("Jervis");
        jervisEndBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jervisEndBtnActionPerformed(evt);
            }
        });

        stephenEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        stephenEndBtn.setText("Stephen's Green");

        bikeTxtOutput.setColumns(20);
        bikeTxtOutput.setRows(5);
        jScrollPane1.setViewportView(bikeTxtOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startLocLbl)
                    .addComponent(heustonStartBtn)
                    .addComponent(stephenStartBtn)
                    .addComponent(jervisStartBtn)
                    .addComponent(nciStartBtn)
                    .addComponent(connollyStartBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endLocLbl)
                    .addComponent(heustonEndBtn)
                    .addComponent(stephenEndBtn)
                    .addComponent(jervisEndBtn)
                    .addComponent(nciEndBtn)
                    .addComponent(connollyEndBtn))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(welcomeBikeLb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(welcomeBikeLb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLocLbl)
                    .addComponent(endLocLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(heustonStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(connollyStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nciStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jervisStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(stephenStartBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(heustonEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(connollyEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nciEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jervisEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(stephenEndBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jervisStartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jervisStartBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jervisStartBtnActionPerformed

    private void jervisEndBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jervisEndBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jervisEndBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bikeTxtOutput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton connollyEndBtn;
    private javax.swing.JRadioButton connollyStartBtn;
    private javax.swing.JLabel endLocLbl;
    private javax.swing.JRadioButton heustonEndBtn;
    private javax.swing.JRadioButton heustonStartBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jervisEndBtn;
    private javax.swing.JRadioButton jervisStartBtn;
    private javax.swing.JRadioButton nciEndBtn;
    private javax.swing.JRadioButton nciStartBtn;
    private javax.swing.JLabel startLocLbl;
    private javax.swing.JRadioButton stephenEndBtn;
    private javax.swing.JRadioButton stephenStartBtn;
    private javax.swing.JLabel welcomeBikeLb;
    // End of variables declaration//GEN-END:variables
}
