/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Aaron_Package;

import javax.swing.JOptionPane;
import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;
import responsibleconsumptionapp.Model.Focus;

/*Classname bikeBookingGUI.java
 * @author Aaron Byrne 24437136
 */
public class bikeBookingGUI extends javax.swing.JPanel implements IControllable {

    /**
     * Creates new form bikeBookingGUI
     */
    private UserInterfaceController UICListener;
    private Focus focus;

    public bikeBookingGUI() {
        initComponents();
    }

    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }

    public void setUserDetails() {
        focus = new Focus(UICListener.getUserService(), UICListener.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButtonGroup = new javax.swing.ButtonGroup();
        endButtonGroup = new javax.swing.ButtonGroup();
        welcomeBikeLb = new javax.swing.JLabel();
        startLocLbl = new javax.swing.JLabel();
        endLocLbl = new javax.swing.JLabel();
        heustonStartBtn = new javax.swing.JRadioButton();
        connollyStartBtn = new javax.swing.JRadioButton();
        nciStartBtn = new javax.swing.JRadioButton();
        jervisStartBtn = new javax.swing.JRadioButton();
        stephenStartBtn = new javax.swing.JRadioButton();
        heustonEndBtn = new javax.swing.JRadioButton();
        connollyEndBtn = new javax.swing.JRadioButton();
        nciEndBtn = new javax.swing.JRadioButton();
        jervisEndBtn = new javax.swing.JRadioButton();
        stephenEndBtn = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JButton();
        confirmSelectBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 54, 99));

        welcomeBikeLb.setBackground(new java.awt.Color(255, 255, 255));
        welcomeBikeLb.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        welcomeBikeLb.setForeground(new java.awt.Color(240, 248, 255));
        welcomeBikeLb.setText("Welcome to the Bike Booking App");
        welcomeBikeLb.setAlignmentX(0.5F);

        startLocLbl.setBackground(new java.awt.Color(255, 255, 255));
        startLocLbl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        startLocLbl.setForeground(new java.awt.Color(240, 248, 255));
        startLocLbl.setText("Please select your starting location");

        endLocLbl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        endLocLbl.setForeground(new java.awt.Color(240, 248, 255));
        endLocLbl.setText("Please select your ending location");

        heustonStartBtn.setBackground(new java.awt.Color(0, 54, 99));
        startButtonGroup.add(heustonStartBtn);
        heustonStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        heustonStartBtn.setForeground(new java.awt.Color(240, 248, 255));
        heustonStartBtn.setText("Heuston Station");

        connollyStartBtn.setBackground(new java.awt.Color(0, 54, 99));
        startButtonGroup.add(connollyStartBtn);
        connollyStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        connollyStartBtn.setForeground(new java.awt.Color(240, 248, 255));
        connollyStartBtn.setText("Connolly Station");

        nciStartBtn.setBackground(new java.awt.Color(0, 54, 99));
        startButtonGroup.add(nciStartBtn);
        nciStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nciStartBtn.setForeground(new java.awt.Color(240, 248, 255));
        nciStartBtn.setText("NCI");

        jervisStartBtn.setBackground(new java.awt.Color(0, 54, 99));
        startButtonGroup.add(jervisStartBtn);
        jervisStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jervisStartBtn.setForeground(new java.awt.Color(240, 248, 255));
        jervisStartBtn.setText("Jervis");

        stephenStartBtn.setBackground(new java.awt.Color(0, 54, 99));
        startButtonGroup.add(stephenStartBtn);
        stephenStartBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        stephenStartBtn.setForeground(new java.awt.Color(240, 248, 255));
        stephenStartBtn.setText("Stephen's Green");

        heustonEndBtn.setBackground(new java.awt.Color(0, 54, 99));
        endButtonGroup.add(heustonEndBtn);
        heustonEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        heustonEndBtn.setForeground(new java.awt.Color(240, 248, 255));
        heustonEndBtn.setText("Heuston Station");

        connollyEndBtn.setBackground(new java.awt.Color(0, 54, 99));
        endButtonGroup.add(connollyEndBtn);
        connollyEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        connollyEndBtn.setForeground(new java.awt.Color(240, 248, 255));
        connollyEndBtn.setText("Connolly Station");

        nciEndBtn.setBackground(new java.awt.Color(0, 54, 99));
        endButtonGroup.add(nciEndBtn);
        nciEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nciEndBtn.setForeground(new java.awt.Color(240, 248, 255));
        nciEndBtn.setText("NCI");

        jervisEndBtn.setBackground(new java.awt.Color(0, 54, 99));
        endButtonGroup.add(jervisEndBtn);
        jervisEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jervisEndBtn.setForeground(new java.awt.Color(240, 248, 255));
        jervisEndBtn.setText("Jervis");

        stephenEndBtn.setBackground(new java.awt.Color(0, 54, 99));
        endButtonGroup.add(stephenEndBtn);
        stephenEndBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        stephenEndBtn.setForeground(new java.awt.Color(240, 248, 255));
        stephenEndBtn.setText("Stephen's Green");

        searchBtn.setBackground(new java.awt.Color(108, 192, 112));
        searchBtn.setText("Search");
        searchBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        confirmSelectBtn.setBackground(new java.awt.Color(108, 192, 112));
        confirmSelectBtn.setText("Confirm");
        confirmSelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSelectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startLocLbl)
                            .addComponent(heustonStartBtn)
                            .addComponent(jervisStartBtn)
                            .addComponent(nciStartBtn)
                            .addComponent(connollyStartBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endLocLbl)
                            .addComponent(heustonEndBtn)
                            .addComponent(stephenEndBtn)
                            .addComponent(jervisEndBtn)
                            .addComponent(nciEndBtn)
                            .addComponent(connollyEndBtn))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stephenStartBtn)
                        .addGap(60, 60, 60)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(confirmSelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(welcomeBikeLb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(welcomeBikeLb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLocLbl)
                    .addComponent(endLocLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(heustonStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(connollyStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nciStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jervisStartBtn)
                        .addGap(18, 18, 18)
                        .addComponent(stephenStartBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(heustonEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(connollyEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nciEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jervisEndBtn)
                        .addGap(18, 18, 18)
                        .addComponent(stephenEndBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmSelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // Heuston as Start
        if (heustonStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (heustonStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to Connolly is a 15 minute journey. (15 points)");
        } else if (heustonStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to NCI is a 18 minute journey. (18 points)");
        } else if (heustonStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to Jervis is a 10 minute journey. (10 points)");
        } else if (heustonStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to Stephen's Green is a 15 minute journey. (15 points)");

            // Connolly as Start
        } else if (connollyStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (connollyStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to Heuston is a 15 minute journey. (15 points)");
        } else if (connollyStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to NCI is a 3 minute journey. (3 points)");
        } else if (connollyStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to Jervis is a 7 minute journey. (7 points)");
        } else if (connollyStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to Stephen's Green is a 7 minute journey. (7 points)");

            // NCI as Start
        } else if (nciStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (nciStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Heuston is a 18 minute journey. (18 points)");
        } else if (nciStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Connolly is a 3 minute journey. (3 points)");
        } else if (nciStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Jervis is a 13 minute journey. (13 points)");
        } else if (nciStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Stephen's Green is a 10 minute journey. (10 points)");

            // Jervis as Start
        } else if (jervisStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (jervisStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to Heuston is a 10 minute journey. (10 points)");
        } else if (jervisStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to Connolly is a 7 minute journey. (7 points)");
        } else if (jervisStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to NCI is a 13 minute journey. (13 points)");
        } else if (jervisStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to Stephen's Green is a 6 minute journey. (6 points)");

            // Stephen's Green as Start
        } else if (stephenStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (stephenStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to Heuston is a 15 minute journey. (15 points)");
        } else if (stephenStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to Connolly is a 7 minute journey. (7 points)");
        } else if (stephenStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to NCI is a 10 minute journey. (10 points)");
        } else if (stephenStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to Jervis is a 6 minute journey. (6 points)");

            // Error Handling: If either no or only one selection is made
        } else {
            JOptionPane.showMessageDialog(this, "Error, please make a starting and ending selection.");
        }


    }//GEN-LAST:event_searchBtnActionPerformed

    private void confirmSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSelectBtnActionPerformed
        //Heuston as Start
        if (heustonStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (heustonStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to Connolly is a 15 minute journey. 15 points will be added");
            focus.addCurrentPoints(15);
        } else if (heustonStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to NCI is a 18 minute journey. 18 points will be added");
            focus.addCurrentPoints(18);

        } else if (heustonStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to Jervis is a 10 minute journey. 10 points will be added");
            focus.addCurrentPoints(10);

        } else if (heustonStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Heuston to Stephen's Green is a 15 minute journey. 15 points will be added");
            focus.addCurrentPoints(15);

            //Connolly as Start
        } else if (connollyStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (connollyStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to Heuston is a 15 minute journey. 15 points will be added");
            focus.addCurrentPoints(15);

        } else if (connollyStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to NCI is a 3 minute journey. 3 points will be added");
            focus.addCurrentPoints(3);

        } else if (connollyStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to Jervis is a 7 minute journey. 7 points will be added");
            focus.addCurrentPoints(7);

        } else if (connollyStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Connolly to Stephen's Green is a 7 minute journey. 7 points will be added");
            focus.addCurrentPoints(7);

            //NCI as Start
        } else if (nciStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (nciStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Heuston is a 18 minute journey. 18 points will be added");
            focus.addCurrentPoints(18);

        } else if (nciStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Connolly is a 3 minute journey. 3 points will be added");
            focus.addCurrentPoints(3);

        } else if (nciStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Jervis is a 13 minute journey. 13 points will be added");
            focus.addCurrentPoints(13);

        } else if (nciStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "NCI to Stephen's Green is a 10 minute journey. 10 points will be added");
            focus.addCurrentPoints(10);

            //Jervis as Start
        } else if (jervisStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (jervisStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to Heuston is a 10 minute journey. 10 points will be added");
            focus.addCurrentPoints(10);

        } else if (jervisStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to Connolly is a 7 minute journey. 7 points will be added");
            focus.addCurrentPoints(7);

        } else if (jervisStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to NCI is a 13 minute journey. 13 points will be added");
            focus.addCurrentPoints(13);

        } else if (jervisStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Jervis to Stephen's Green is a 6 minute journey. 6 points will be added");
            focus.addCurrentPoints(6);

            //Stephen's Green as Start
        } else if (stephenStartBtn.isSelected() && stephenEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select two different locations");
        } else if (stephenStartBtn.isSelected() && heustonEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to Heuston is a 15 minute journey. 15 points will be added");
            focus.addCurrentPoints(15);

        } else if (stephenStartBtn.isSelected() && connollyEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to Connolly is a 7 minute journey. 7 points will be added");
            focus.addCurrentPoints(7);

        } else if (stephenStartBtn.isSelected() && nciEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to NCI is a 10 minute journey. 10 points will be added");
            focus.addCurrentPoints(10);

        } else if (stephenStartBtn.isSelected() && jervisEndBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Stephen's Green to Jervis is a 6 minute journey. 6 points will be added");
            focus.addCurrentPoints(6);

        } else {
            JOptionPane.showMessageDialog(this, "Error, please make two valid selections");

        }

    }//GEN-LAST:event_confirmSelectBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmSelectBtn;
    private javax.swing.JRadioButton connollyEndBtn;
    private javax.swing.JRadioButton connollyStartBtn;
    private javax.swing.ButtonGroup endButtonGroup;
    private javax.swing.JLabel endLocLbl;
    private javax.swing.JRadioButton heustonEndBtn;
    private javax.swing.JRadioButton heustonStartBtn;
    private javax.swing.JRadioButton jervisEndBtn;
    private javax.swing.JRadioButton jervisStartBtn;
    private javax.swing.JRadioButton nciEndBtn;
    private javax.swing.JRadioButton nciStartBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.ButtonGroup startButtonGroup;
    private javax.swing.JLabel startLocLbl;
    private javax.swing.JRadioButton stephenEndBtn;
    private javax.swing.JRadioButton stephenStartBtn;
    private javax.swing.JLabel welcomeBikeLb;
    // End of variables declaration//GEN-END:variables
}
