/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Aaron_Package;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *
 * @author gamer
 */
public class custFeedbackGUI extends javax.swing.JPanel implements IControllable {

    /**
     * Creates new form custFeedbackGUI
     */
    private UserInterfaceController UICListener;

    public custFeedbackGUI() {
        initComponents();
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTourLbl = new javax.swing.JLabel();
        selectTransportLbl = new javax.swing.JLabel();
        yesTourBtn = new javax.swing.JButton();
        noTourBtn = new javax.swing.JButton();
        yesTourBtn1 = new javax.swing.JButton();
        noTourBtn1 = new javax.swing.JButton();
        selectTransportLbl1 = new javax.swing.JLabel();
        selectTransportLbl2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        selectTransportLbl3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        yesTourBtn2 = new javax.swing.JButton();

        welcomeTourLbl.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        welcomeTourLbl.setText("Welcome to the feedback form");
        welcomeTourLbl.setAlignmentX(0.5F);

        selectTransportLbl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        selectTransportLbl.setText("Would you reccomend this service to a friend?");

        yesTourBtn.setBackground(new java.awt.Color(90, 100, 49));
        yesTourBtn.setText("Yes");

        noTourBtn.setBackground(new java.awt.Color(255, 0, 0));
        noTourBtn.setText("No");

        yesTourBtn1.setBackground(new java.awt.Color(90, 100, 49));
        yesTourBtn1.setText("Yes");

        noTourBtn1.setBackground(new java.awt.Color(255, 0, 0));
        noTourBtn1.setText("No");

        selectTransportLbl1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        selectTransportLbl1.setText("Was the service easy to use?");

        selectTransportLbl2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        selectTransportLbl2.setText("How would you rate the tourism app on a scale of 1-10?");

        selectTransportLbl3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        selectTransportLbl3.setText("Do you have any feedback about the tourism app?");

        jTextField1.setText("Please insert here");

        yesTourBtn2.setBackground(new java.awt.Color(0, 0, 255));
        yesTourBtn2.setText("Submit");
        yesTourBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesTourBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yesTourBtn)
                        .addGap(18, 18, 18)
                        .addComponent(noTourBtn)
                        .addGap(432, 432, 432))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesTourBtn1)
                        .addGap(18, 18, 18)
                        .addComponent(noTourBtn1)
                        .addGap(426, 426, 426))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(selectTransportLbl1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectTransportLbl2)
                            .addComponent(selectTransportLbl)
                            .addComponent(selectTransportLbl3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(yesTourBtn2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(welcomeTourLbl)))
                .addGap(0, 219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(welcomeTourLbl)
                .addGap(18, 18, 18)
                .addComponent(selectTransportLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesTourBtn)
                    .addComponent(noTourBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTransportLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesTourBtn1)
                    .addComponent(noTourBtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTransportLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTransportLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yesTourBtn2)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yesTourBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesTourBtn2ActionPerformed
        // TODO add your handling code here:
        UICListener.changePanel("tourism");
    }//GEN-LAST:event_yesTourBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton noTourBtn;
    private javax.swing.JButton noTourBtn1;
    private javax.swing.JLabel selectTransportLbl;
    private javax.swing.JLabel selectTransportLbl1;
    private javax.swing.JLabel selectTransportLbl2;
    private javax.swing.JLabel selectTransportLbl3;
    private javax.swing.JLabel welcomeTourLbl;
    private javax.swing.JButton yesTourBtn;
    private javax.swing.JButton yesTourBtn1;
    private javax.swing.JButton yesTourBtn2;
    // End of variables declaration//GEN-END:variables
}
