/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Aaron_Package;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *
 * @author gamer
 */
public class tourismRouteGUI extends javax.swing.JPanel implements IControllable{

    /**
     * Creates new form tourismRouteGUI
     */
    private UserInterfaceController UICListener;

    public tourismRouteGUI() {
        initComponents();
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeTourLbl = new javax.swing.JLabel();
        selectTransportLbl = new javax.swing.JLabel();
        busBtn = new javax.swing.JRadioButton();
        taxiBtn = new javax.swing.JRadioButton();
        luasBtn = new javax.swing.JRadioButton();
        trainBtn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tourText = new javax.swing.JTextArea();
        selectTransportLbl1 = new javax.swing.JLabel();
        yesTourBtn = new javax.swing.JButton();
        noTourBtn = new javax.swing.JButton();

        welcomeTourLbl.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        welcomeTourLbl.setText("Welcome to the Tourism Route App");
        welcomeTourLbl.setAlignmentX(0.5F);

        selectTransportLbl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        selectTransportLbl.setText("Please select a mode of transport");

        busBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        busBtn.setText("Bus");

        taxiBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        taxiBtn.setText("Taxi");

        luasBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        luasBtn.setText("Luas");
        luasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasBtnActionPerformed(evt);
            }
        });

        trainBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        trainBtn.setText("Train");
        trainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainBtnActionPerformed(evt);
            }
        });

        tourText.setColumns(20);
        tourText.setRows(5);
        jScrollPane1.setViewportView(tourText);

        selectTransportLbl1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        selectTransportLbl1.setText("Accept destination and method?");

        yesTourBtn.setBackground(new java.awt.Color(90, 100, 49));
        yesTourBtn.setText("Yes");

        noTourBtn.setBackground(new java.awt.Color(255, 0, 0));
        noTourBtn.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeTourLbl)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luasBtn)
                                    .addComponent(taxiBtn)
                                    .addComponent(busBtn))
                                .addGap(231, 231, 231)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yesTourBtn)
                                    .addComponent(noTourBtn))))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectTransportLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectTransportLbl1)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(welcomeTourLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectTransportLbl)
                    .addComponent(selectTransportLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(taxiBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(luasBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yesTourBtn)
                        .addGap(32, 32, 32)
                        .addComponent(noTourBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trainBtn)
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void luasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasBtnActionPerformed

    private void trainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton busBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton luasBtn;
    private javax.swing.JButton noTourBtn;
    private javax.swing.JLabel selectTransportLbl;
    private javax.swing.JLabel selectTransportLbl1;
    private javax.swing.JRadioButton taxiBtn;
    private javax.swing.JTextArea tourText;
    private javax.swing.JRadioButton trainBtn;
    private javax.swing.JLabel welcomeTourLbl;
    private javax.swing.JButton yesTourBtn;
    // End of variables declaration//GEN-END:variables
}
