/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Aaron_Package;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *Classname tourismHomePanel.java
 * @author Aaron Bynre 24437136
 */
public class tourismHomePanel extends javax.swing.JPanel implements IControllable {

    private UserInterfaceController UICListener;

    public tourismHomePanel() {
        initComponents();
    }

    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        welcomeMsgLbl = new javax.swing.JLabel();
        bikeBookLbl = new javax.swing.JLabel();
        custFeedbackLbl = new javax.swing.JLabel();
        bikeBookingBtn = new javax.swing.JButton();
        surveyBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(204, 204, 255));

        welcomeMsgLbl.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        welcomeMsgLbl.setForeground(new java.awt.Color(0, 0, 0));
        welcomeMsgLbl.setText("Welcome to the Tourism App");

        bikeBookLbl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bikeBookLbl.setForeground(new java.awt.Color(0, 0, 0));
        bikeBookLbl.setText("Click below for bike booking");

        custFeedbackLbl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        custFeedbackLbl.setForeground(new java.awt.Color(0, 0, 0));
        custFeedbackLbl.setText("Click below for the survey");

        bikeBookingBtn.setBackground(new java.awt.Color(0, 54, 99));
        bikeBookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        bikeBookingBtn.setText("Bike Book");
        bikeBookingBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bikeBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikeBookingBtnActionPerformed(evt);
            }
        });

        surveyBtn.setBackground(new java.awt.Color(159, 43, 104));
        surveyBtn.setForeground(new java.awt.Color(255, 255, 255));
        surveyBtn.setText("Survey");
        surveyBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        surveyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(bikeBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bikeBookLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(custFeedbackLbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(surveyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(welcomeMsgLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(welcomeMsgLbl)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bikeBookLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bikeBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(custFeedbackLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(surveyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bikeBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikeBookingBtnActionPerformed
        UICListener.changePanel("bikeBooking");//change to the bikeBookingGUI
    }//GEN-LAST:event_bikeBookingBtnActionPerformed

    private void surveyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surveyBtnActionPerformed
        UICListener.changePanel("customerFeedback");//change to the custFeedbackGUI
    }//GEN-LAST:event_surveyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bikeBookLbl;
    private javax.swing.JButton bikeBookingBtn;
    private javax.swing.JLabel custFeedbackLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton surveyBtn;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
