/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.View;

/*
 * Classname LoginPanel.java
 * Date 11/10/2025
 * @author Lorenzo Moares Nunez, 23378441
 */
import javax.swing.JOptionPane;
import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

public class LoginPanel extends javax.swing.JPanel implements IControllable {

    /**
     * Creates new form TestPanel
     */
    private UserInterfaceController UICListener;

    public LoginPanel() {
        initComponents();
    }

    //required for userinterfacecontroller to react to events on Login Panel
    //subscriber is ui controller - awaiting event to run code
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }

    public String getExistingUserPassword() {
        char[] pw = existingUserPassword.getPassword();
        String pwText = new String(pw);

        return pwText;
    }

    public String getNewUserPassword() {
        char[] pw = newUserPassword.getPassword();
        String pwText = new String(pw);

        return pwText;
    }

    public void resetAllFields() {
        this.newUserUsername.setText("");
        this.newUserPassword.setText("");
        this.newUserFullName.setText("");
        this.existingUserUsername.setText("");
        this.existingUserPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        newUserLBL = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        existingUserPassword = new javax.swing.JPasswordField();
        newUserPassword = new javax.swing.JPasswordField();
        newUserPwLBL = new javax.swing.JLabel();
        loginUnLBL = new javax.swing.JLabel();
        existingUserUsername = new javax.swing.JTextField();
        newUserUsername = new javax.swing.JTextField();
        loginPwLBL = new javax.swing.JLabel();
        newUserUnLBL = new javax.swing.JLabel();
        newUserFullName = new javax.swing.JTextField();
        newUserFnLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        groupLBL = new javax.swing.JLabel();
        adminCredsBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        loginLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginLBL.setText("Login Existing User");

        newUserLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        newUserLBL.setText("Register New User");

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        existingUserPassword.setColumns(8);

        newUserPassword.setColumns(8);
        newUserPassword.setToolTipText("Enter Password");
        newUserPassword.setActionCommand("<Not Set>");

        newUserPwLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newUserPwLBL.setText("Password");

        loginUnLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginUnLBL.setText("Username");

        loginPwLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginPwLBL.setText("Password");

        newUserUnLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newUserUnLBL.setText("Username");

        newUserFnLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newUserFnLBL.setText("Full Name");

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setText("Responsible Consumption");

        groupLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        groupLBL.setText("Group H - Lorenzo Moares Nunez, Jean Walton, Aaron Byrne");

        adminCredsBTN.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        adminCredsBTN.setText("Admin Credentials");
        adminCredsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCredsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLBL)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(groupLBL)))
                .addGap(0, 211, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newUserFnLBL)
                    .addComponent(newUserLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newUserUnLBL)
                            .addComponent(newUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newUserPwLBL)
                                .addGap(24, 24, 24))
                            .addComponent(newUserPassword)))
                    .addComponent(newUserFullName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginUnLBL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(existingUserPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(existingUserUsername, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginPwLBL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginLBL))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(adminCredsBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(groupLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newUserLBL)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newUserUnLBL)
                            .addComponent(newUserPwLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newUserFnLBL)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(newUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginLBL)
                        .addGap(18, 18, 18)
                        .addComponent(loginUnLBL)
                        .addGap(5, 5, 5)
                        .addComponent(existingUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginPwLBL)
                        .addGap(5, 5, 5)
                        .addComponent(existingUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminCredsBTN)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if(newUserUsername.getText().isEmpty() || newUserFullName.getText().isEmpty() || getNewUserPassword().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please fill in all fields to register new user");
        }else if (UICListener != null) {
            //call UI Controller to send user data for account creation
            UICListener.onRegisterButtonClicked(newUserUsername.getText(), newUserFullName.getText(), getNewUserPassword());
            //resets input fields to default
            resetAllFields();
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        //Ensures UICListener has been correctly referenced
        if(existingUserUsername.getText().isEmpty() || getExistingUserPassword().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please fill in all fields to login existing user");
        }else if (UICListener != null) {
            //call UI Controller to send user data for account verification
            UICListener.onLoginButtonClicked(existingUserUsername.getText(), getExistingUserPassword());
            resetAllFields();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void adminCredsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCredsBTNActionPerformed
        existingUserUsername.setText("admin");
        existingUserPassword.setText("admin");
    }//GEN-LAST:event_adminCredsBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminCredsBTN;
    private javax.swing.JPasswordField existingUserPassword;
    private javax.swing.JTextField existingUserUsername;
    private javax.swing.JLabel groupLBL;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLBL;
    private javax.swing.JLabel loginPwLBL;
    private javax.swing.JLabel loginUnLBL;
    private javax.swing.JLabel newUserFnLBL;
    private javax.swing.JTextField newUserFullName;
    private javax.swing.JLabel newUserLBL;
    private javax.swing.JPasswordField newUserPassword;
    private javax.swing.JLabel newUserPwLBL;
    private javax.swing.JLabel newUserUnLBL;
    private javax.swing.JTextField newUserUsername;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
