/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.View;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *
 * @author moare
 */
public class NewUserRegistration extends javax.swing.JPanel implements IControllable {
    private UserInterfaceController UICListener;

    /**
     * Creates new form NewUserRegistration
     */
    public NewUserRegistration() {
        initComponents();
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        travelOptionsBG = new javax.swing.ButtonGroup();
        panelLBL = new javax.swing.JLabel();
        headerLBL = new javax.swing.JLabel();
        redMeatCB = new javax.swing.JCheckBox();
        plantMealCB = new javax.swing.JCheckBox();
        renewableCB = new javax.swing.JCheckBox();
        compostCB = new javax.swing.JCheckBox();
        airTravelCB = new javax.swing.JCheckBox();
        submitBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bicycleRB = new javax.swing.JRadioButton();
        publicTransRB = new javax.swing.JRadioButton();
        personalVehicleRB = new javax.swing.JRadioButton();
        gasOilCoalCB = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();

        panelLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelLBL.setText("New User Registration");

        headerLBL.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        headerLBL.setText("Check any of the following boxes to calculate your individual Carbon Footprint Score");

        redMeatCB.setText("Regularly Consume Red Meat");

        plantMealCB.setText("Regularly Consume Plant-based Meals");

        renewableCB.setText("Home Utilizes Renewable Energy Solutions");

        compostCB.setText("Regularly Compost Organic Waste");
        compostCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compostCBActionPerformed(evt);
            }
        });

        airTravelCB.setText("Frequently Use Air Travel");
        airTravelCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airTravelCBActionPerformed(evt);
            }
        });

        submitBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Modes of Travel / Commute");

        travelOptionsBG.add(bicycleRB);
        bicycleRB.setText("Bicycle / Walking");

        travelOptionsBG.add(publicTransRB);
        publicTransRB.setText("Public Transportation / Car-pool");

        travelOptionsBG.add(personalVehicleRB);
        personalVehicleRB.setText("Personal Vehicle");
        personalVehicleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalVehicleRBActionPerformed(evt);
            }
        });

        gasOilCoalCB.setText("Home Utilizes Natural Gas, Oil, and/or Coal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plantMealCB)
                            .addComponent(renewableCB)
                            .addComponent(redMeatCB))
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compostCB)
                            .addComponent(gasOilCoalCB)
                            .addComponent(airTravelCB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bicycleRB)
                                .addGap(33, 33, 33)
                                .addComponent(publicTransRB)
                                .addGap(39, 39, 39)
                                .addComponent(personalVehicleRB))))
                    .addComponent(headerLBL)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(panelLBL)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelLBL)
                .addGap(37, 37, 37)
                .addComponent(headerLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redMeatCB)
                    .addComponent(compostCB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plantMealCB)
                    .addComponent(airTravelCB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renewableCB)
                    .addComponent(gasOilCoalCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bicycleRB)
                    .addComponent(personalVehicleRB)
                    .addComponent(publicTransRB))
                .addGap(18, 18, 18)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        UICListener.registrationComplete(100);
    }//GEN-LAST:event_submitBTNActionPerformed

    private void personalVehicleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalVehicleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalVehicleRBActionPerformed

    private void compostCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compostCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compostCBActionPerformed

    private void airTravelCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airTravelCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airTravelCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox airTravelCB;
    private javax.swing.JRadioButton bicycleRB;
    private javax.swing.JCheckBox compostCB;
    private javax.swing.JCheckBox gasOilCoalCB;
    private javax.swing.JLabel headerLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel panelLBL;
    private javax.swing.JRadioButton personalVehicleRB;
    private javax.swing.JCheckBox plantMealCB;
    private javax.swing.JRadioButton publicTransRB;
    private javax.swing.JCheckBox redMeatCB;
    private javax.swing.JCheckBox renewableCB;
    private javax.swing.JButton submitBTN;
    private javax.swing.ButtonGroup travelOptionsBG;
    // End of variables declaration//GEN-END:variables
}
