/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.View;

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;

/**
 *
 * @author moare
 */
public class NewUserRegistration extends javax.swing.JPanel implements IControllable {
    private UserInterfaceController UICListener;

    /**
     * Creates new form NewUserRegistration
     */
    public NewUserRegistration() {
        initComponents();
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        travelOptionsBG = new javax.swing.ButtonGroup();
        panelLBL = new javax.swing.JLabel();
        headerLBL = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        submitBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bicycleRB = new javax.swing.JRadioButton();
        publicTransRB = new javax.swing.JRadioButton();
        personalVehicleRB = new javax.swing.JRadioButton();
        jCheckBox6 = new javax.swing.JCheckBox();

        panelLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        panelLBL.setText("New User Registration");

        headerLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        headerLBL.setText("Check any of the following boxes to calculate your individual Carbon Footprint Score");

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jCheckBox3.setText("jCheckBox3");

        jCheckBox4.setText("jCheckBox4");

        jCheckBox5.setText("jCheckBox5");

        submitBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Modes of Travel / Commute");

        travelOptionsBG.add(bicycleRB);
        bicycleRB.setText("Bicycle / Walking");

        travelOptionsBG.add(publicTransRB);
        publicTransRB.setText("Public Transportation / Car-pool");

        travelOptionsBG.add(personalVehicleRB);
        personalVehicleRB.setText("Personal Vehicle");
        personalVehicleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalVehicleRBActionPerformed(evt);
            }
        });

        jCheckBox6.setText("jCheckBox6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bicycleRB)
                        .addGap(33, 33, 33)
                        .addComponent(publicTransRB)
                        .addGap(39, 39, 39)
                        .addComponent(personalVehicleRB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(headerLBL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLBL)
                .addGap(41, 41, 41)
                .addComponent(headerLBL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bicycleRB)
                    .addComponent(personalVehicleRB)
                    .addComponent(publicTransRB))
                .addGap(18, 18, 18)
                .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        // TODO add your handling code here:
        UICListener.registrationComplete(100);
    }//GEN-LAST:event_submitBTNActionPerformed

    private void personalVehicleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalVehicleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalVehicleRBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bicycleRB;
    private javax.swing.JLabel headerLBL;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel panelLBL;
    private javax.swing.JRadioButton personalVehicleRB;
    private javax.swing.JRadioButton publicTransRB;
    private javax.swing.JButton submitBTN;
    private javax.swing.ButtonGroup travelOptionsBG;
    // End of variables declaration//GEN-END:variables
}
