/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.View;

import javax.swing.JOptionPane;
import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;
import responsibleconsumptionapp.Model.User;

/*
 * Classname UserPortal.java
 * Date 16/11/2025
 * @author Lorenzo Moares Nunez, 23378441
 */
public class UserPortal extends javax.swing.JPanel implements IControllable{

    /**
     * Creates new form UserPortal
     */
    UserInterfaceController UICListener;
    User user;
    
    public UserPortal() {
        initComponents();
        userTA.setEditable(false);
    }
    
    public void setUser(){
        this.user = UICListener.getUser();
        userFnLBL.setText(user.getName());
        userCfLBL.setText(user.getCf_score()+"");
        userEfLBL.setText(user.getEf_score()+"");
    }
    
    public void updateEFScore() {
        userEfLBL.setText(user.getEf_score()+"");
    }
    
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        userFnHeaderLBL = new javax.swing.JLabel();
        userFnLBL = new javax.swing.JLabel();
        userCfHeaderLBL = new javax.swing.JLabel();
        userCfLBL = new javax.swing.JLabel();
        logoutBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTA = new javax.swing.JTextArea();
        userEfHeaderLBL = new javax.swing.JLabel();
        userEfLBL = new javax.swing.JLabel();
        leaderboardBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setText("Responsible Consumption");

        userFnHeaderLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userFnHeaderLBL.setText("Welcome");

        userFnLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userFnLBL.setLabelFor(userFnLBL);
        userFnLBL.setText("FULLNAME");

        userCfHeaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userCfHeaderLBL.setText("Carbon Footprint Score: ");

        userCfLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userCfLBL.setText("0");

        logoutBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutBTN.setText("Logout");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));

        userTA.setColumns(20);
        userTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userTA.setRows(5);
        userTA.setText("\t              --- Responsible Consumption ---\n           Welcome to the Responsible Consumption prototype application.\n\nThis application is based off of the 12th United Nations goals for sustainable\nconsumption - Resonsible Consumption.\n\nUse the navbar to navigate between the 3 sections of this application.\n - Click Chemical Waste to learn about recycling methods, safety, and log recycling.\n - Click Tourism & Travel to learn about responsible tourism\n - Click Sustainable Consumption to learn about eco-friendly energy solutions.");
        jScrollPane1.setViewportView(userTA);

        userEfHeaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userEfHeaderLBL.setText("Eco-Friendly Score:");

        userEfLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userEfLBL.setText("0");

        leaderboardBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        leaderboardBTN.setText("Leaderboard");
        leaderboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userFnHeaderLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userFnLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(userEfHeaderLBL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userEfLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(userCfHeaderLBL)
                            .addGap(18, 18, 18)
                            .addComponent(userCfLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leaderboardBTN))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleLBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFnHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userFnLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCfHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCfLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEfHeaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userEfLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaderboardBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        UICListener.removeNavbar();
        UICListener.saveUserChanges();
        UICListener.changePanel("Login");
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void leaderboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardBTNActionPerformed
        JOptionPane.showMessageDialog(this,"LeaderBoard:\n1: ...\n2: ...\n3: ...\n...");
    }//GEN-LAST:event_leaderboardBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leaderboardBTN;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel userCfHeaderLBL;
    private javax.swing.JLabel userCfLBL;
    private javax.swing.JLabel userEfHeaderLBL;
    private javax.swing.JLabel userEfLBL;
    private javax.swing.JLabel userFnHeaderLBL;
    private javax.swing.JLabel userFnLBL;
    private javax.swing.JTextArea userTA;
    // End of variables declaration//GEN-END:variables
}
