/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Jean_Package;

/**
 * ChemicalWasteGui.java
 * Date 11/11/2025
 * @author Jeán Walton
 */

import javax.swing.JOptionPane;
import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;


public class ChemicalWasteGUI extends javax.swing.JPanel implements IControllable{
    private UserInterfaceController UICListener;
    private String wasteType = "";
    
    /**
     * Creates new form ChemicalWasteGUI
     */
    public ChemicalWasteGUI() {
        initComponents();
        
       
    
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        recyclable_waste_R_btn = new javax.swing.JRadioButton();
        non_recyclable_R_btn = new javax.swing.JRadioButton();
        goods_recycling_image = new javax.swing.JLabel();
        proceed = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Chemical Waste");

        recyclable_waste_R_btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup.add(recyclable_waste_R_btn);
        recyclable_waste_R_btn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        recyclable_waste_R_btn.setForeground(new java.awt.Color(0, 153, 0));
        recyclable_waste_R_btn.setText("Recyclable Waste");
        recyclable_waste_R_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recyclable_waste_R_btnActionPerformed(evt);
            }
        });

        non_recyclable_R_btn.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup.add(non_recyclable_R_btn);
        non_recyclable_R_btn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        non_recyclable_R_btn.setForeground(new java.awt.Color(204, 0, 51));
        non_recyclable_R_btn.setText("NON-Recyclable Waste");
        non_recyclable_R_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                non_recyclable_R_btnActionPerformed(evt);
            }
        });

        goods_recycling_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsibleconsumptionapp/Resources/Jean_Resource/goods_recycling.png"))); // NOI18N
        goods_recycling_image.setText("jLabel2");
        goods_recycling_image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        proceed.setBackground(new java.awt.Color(204, 0, 204));
        proceed.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        proceed.setForeground(new java.awt.Color(0, 0, 0));
        proceed.setText("PROCEED");
        proceed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recyclable_waste_R_btn)
                    .addComponent(non_recyclable_R_btn)
                    .addComponent(proceed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(goods_recycling_image, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recyclable_waste_R_btn)
                        .addGap(51, 51, 51)
                        .addComponent(non_recyclable_R_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(goods_recycling_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        // TODO add your handling code here:
        //Error pop up if a radio button is not selected
        if(wasteType != ""){
            UICListener.changePanel(wasteType);
            System.out.println(this.UICListener.getUser());
        }else{
           JOptionPane.showMessageDialog(this, "Must select Recyclable or Non-Recyclable");
        }
        
    }//GEN-LAST:event_proceedActionPerformed
    //radio button choices(must be selected)
    private void recyclable_waste_R_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recyclable_waste_R_btnActionPerformed
        // TODO add your handling code here:
        wasteType = "Recyclable";
    }//GEN-LAST:event_recyclable_waste_R_btnActionPerformed

    private void non_recyclable_R_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_non_recyclable_R_btnActionPerformed
        // TODO add your handling code here:
        wasteType = "NonRecyclable";
    }//GEN-LAST:event_non_recyclable_R_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel goods_recycling_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton non_recyclable_R_btn;
    private javax.swing.JButton proceed;
    private javax.swing.JRadioButton recyclable_waste_R_btn;
    // End of variables declaration//GEN-END:variables
}
