/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package responsibleconsumptionapp.Jean_Package;

/**
 *
 * @author walco
 */

import responsibleconsumptionapp.Controller.IControllable;
import responsibleconsumptionapp.Controller.UserInterfaceController;


public class ChemicalWasteGUI extends javax.swing.JPanel implements IControllable{
    private UserInterfaceController UICListener;
    /**
     * Creates new form ChemicalWasteGUI
     */
    public ChemicalWasteGUI() {
        initComponents();
        
       
    
    }
    
    @Override
    public void setPanelListener(UserInterfaceController UICListener) {
        this.UICListener = UICListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        recyclable_waste_R_btn = new javax.swing.JRadioButton();
        non_recyclable_R_btn = new javax.swing.JRadioButton();
        return_button = new javax.swing.JButton();
        goods_recycling_image = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Chemical Waste");

        buttonGroup.add(recyclable_waste_R_btn);
        recyclable_waste_R_btn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        recyclable_waste_R_btn.setForeground(new java.awt.Color(0, 153, 0));
        recyclable_waste_R_btn.setText("Recyclable Waste");

        buttonGroup.add(non_recyclable_R_btn);
        non_recyclable_R_btn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        non_recyclable_R_btn.setForeground(new java.awt.Color(204, 0, 51));
        non_recyclable_R_btn.setText("NON-Recyclable Waste");

        return_button.setBackground(new java.awt.Color(0, 204, 204));
        return_button.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        return_button.setForeground(new java.awt.Color(0, 0, 0));
        return_button.setText("Return");

        goods_recycling_image.setIcon(new javax.swing.ImageIcon("C:\\Users\\walco\\Downloads\\goods_recycling.png")); // NOI18N
        goods_recycling_image.setText("jLabel2");
        goods_recycling_image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recyclable_waste_R_btn)
                    .addComponent(return_button)
                    .addComponent(non_recyclable_R_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(goods_recycling_image, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recyclable_waste_R_btn)
                        .addGap(51, 51, 51)
                        .addComponent(non_recyclable_R_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(return_button))
                    .addComponent(goods_recycling_image, javax.swing.GroupLayout.PREFERRED_SIZE, 375, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel goods_recycling_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton non_recyclable_R_btn;
    private javax.swing.JRadioButton recyclable_waste_R_btn;
    private javax.swing.JButton return_button;
    // End of variables declaration//GEN-END:variables
}
